### PR TITLE
Refactoring to use 'bottleneck' instead of hand-written command queue to throttle hue api command executions

### LINKED ISSUE #40: Verzögerte Reaktion bei v1.0.0
Bei der Version 1.0.0 ist mir aufgefallen, dass ich regelmäßig eine Verzögerung/Latenz von 2- 10 Sekunden habe.

Unabhängig davon ob ich HUE Lampen per Alexa-Sprachbefehl, oder direkt über einen Schalter (Homematic-wired) schalte, die Ausführung erfolgt immer verzögert.

Nach dem Rückgang auf die HUE-Adapter Version 0.6.9 waren die Verzögerungen/Latenzen wieder verschwunden und die HUE Lampen wurden wie gewohnt direkt geschaltet.

### PR DESCRIPTION
**Pull request by jens-maus**
This PR consists of a huge refactoring of the hue api command execution queue that is currently hand written in the iobroker.hue adapter to be able to better comply with the general Philips HUE Api query limits (10 cmds/1 second for light resource requests, 1 cmd/1 sec for group resource requests). To do so, it replaces this hand written command queue by using the `bottleneck` nodejs package (https://github.com/SGrondin/bottleneck) to actually schedule all command executions in two separate rate limiting bottleneck queues (one for `light` and one for `group` requests). This includes scheduling `set`-Requests with a higher priority than regular polling `get`-Requests.

Furthermore, this PR fixes some additional minor problems (e.g. not all parameters were correctly queried from all Philips sensor types correctly).

This PR refs and fixes #40 and #45.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you. I will check it  :)

**Comment by jens-maus** [comment]
Please note, that this change raises the minimum required NodeJS version for ioBroker.hue to v6+ because the bottleneck module requires nodejs v6 as a minimum. This should, however, not be a problem anymore since we are at NodeJS v8 for the LTS version.

Looking forward to see this change integrated soon.

**Comment by GermanBluefox** [comment]
Hi Jens, 
I implemented rather good optimization here:
https://github.com/ioBroker/ioBroker.hue/blob/master/main.js#L487

It combines similar commands to one command and it was used e.g in controlling of RGB or other lamps with more than one state.
Is it possible to integrate is somehow? Because it did from 3 (r, g, b) commands just one request.

**Comment by GermanBluefox** [comment]
What is your experience with modifications here?

**Comment by jens-maus** [comment]
@GermanBluefox I have seen this "combine commands" thing. However, I am still not sure why you would need this? Can you please show a use case for this? IMHO this is a kind of optimization the ioBroker user itself would have to do in their programming rather than the adapter to actually having to perform such optimizations. So if you can show me a use case (actual code) I could see if there is a way to implement a similar command execution optimization in my bottleneck approach.

**Comment by Apollon77** [comment]
I can kind of understand that approach to combine different settings to the same device in one call vs each call one state. If you update a new RGB value in ioBroker (and do not have a compubed rgb field, but use the r, g,and b states then your only way is to do three state updates (r,g,b), but  for sending it out it woud be better to combine them into one call - else you would end up in color disco ;-)
Shelly adapter has same topic ... here we simply defined that it is sended out as requested and added a "custom" rgb state if you want tochange the full color as kind of helper state.

For hue it is mainly (in my opinion): to stay backward compatible the same optimization would be needed too because users may have used it exactly that way and changing this would be kind if breaking ...

**Comment by jens-maus** [comment]
But what happens if the user would actually want to have that "color disco"? By combining commands and removing commands from the queue you would actually remove that possibility and don't give the user the possibility to e.g. change r then g and then b after another, as far as I understand it. IMHO it would be a better/smoother approach to actually introduce a dedicated "rgb" state where you could e.g. submit the rgb color mode in web colors "#FFAABB" and then the adapter converts this into a single command. Or a ioBroker user should be instructed to actually use the `command` state to actually send such combined commands on his own. Otherwise, I really fear that by adding such logic into the adapter you would take away certain possibilities from the adapter interface (e.g. user wants to have a color disco kind of thing).

**Comment by GermanBluefox** [comment]
Alexa controls hue, saturation and brightness in 3 different steps. Because not all adapters supports combined command.

**Comment by GermanBluefox** [comment]
And if you want the color disco, just make a bigger pauses between commands.

**Comment by jens-maus** [comment]
But then you lose the possibility of a fast disco and you never know if one of the commands have not yet been sent out already to the Philips API.

And how does Alexa send out hue/saturation/bridghtness in 3 different steps? You mean the alexa->ioBroker bridge or in general? Because I can perfectly use the Alexa->PhilipsBridge and don't see that when I give a command to change the color it will send multiple commands. I really still feel taking away the possibility to be sure that each command send to the iobroker.hue adapter is actually directly sent to the bridge makes the whole hue adapter somewhat unreliable. Because when I send a command to set "r" to a certain value I have to be sure that it will be directly sent to the bridge or otherwise I cannot really rely on it, because I cannot know how long I really have to pause before I can send the next command.

IMHO it would still be better to actually introduce a new combined "rgb" state for each light+group and if this rgb state is set to a certain value (e.g. based on a webcolor code) the hue adapter can send out a single command with the three r+g+b values. Then users directly wanting to set the rgb value should use this new state instead. I can modify the adapter accordingly. What do you think?

**Comment by Pmant** [comment]
I'd rather have a simplistic hue adapter which just reflects the states that are actually supported by the hue bridge instead of an adapter with all kinds of logics and conversions that only work for a specific environment / situation. Maybe another hue adapter is necessary? Also keep in mind that RGB is a bad choice for lighting colors since there is no black light und you don't get the expected colors.

**Comment by GermanBluefox** [comment]
Look at this code:
https://github.com/ioBroker/ioBroker.cloud/blob/master/lib/alexaSmartHomeV2.js#L933

The world of RGB is not only PhilipsHUE. There are milight, shelly, artnet, osram and... others.

**Comment by jens-maus** [comment]
@GermanBluefox I fully understand your reasoning, but to me this still reads like there is a somewhat shortcoming/missing feature in ioBroker which is tried to be worked around in each and every adapter now. I understand that you currently don't have any mechanism in ioBroker to combine multiple `setForeignState()` executions into a single one. But perhaps that would be something that would be better suited/implemented in the ioBroker core instead. Perhaps something like a `addForeignStateQueue('set', ....)` function that allows to add a certain operation to a kind of command queue and then have a function `executeStateQueue()` function that will send out/process  the collected command queue and perhaps send a message to each adapter about this and if there is a sort of `stateQueue` functionality/callback function implemented in the adapter it could get this queue and then (in case of Philips HUE) combine this into a single command and send it out accordingly. But generally trying to optimize ALL kind of command executions by throwing away consecutive state changes does not sound like a very good idea to me because I still feel that every call to `setForeignState()` should be guaranteed to be correctly/directly processed by the adapter and not some "magic"/logic being apply which potentially the user isn't aware of or doesn't expect to happen.

**Comment by jens-maus** [comment]
Or how about adding a kind of `delayed` option to `setForeignState()` so that an adapter receives a state change with the additional information that "there is more to come". And then in the last `setForeignState()` you add another option to actually finalize the foreign state call changes? This would allow an adapter to actually analyze these options and in case it supports such combined command executions (like Philips HUE) to create an own internal queue first and then wait for the finalize option to be send with one of the `setForgeinState()` executions and then simply combine the queue to a single command queue. How about that?

**Comment by Apollon77** [comment]
@jens-maus Some more would be needed then what you describe. we would also need definitions of "which states belong together" and some more things. This would be it's own js-controller feature request and would then be available in a future js-controller version. Also for the "there comes more" flagging.

So nothing that helps now.

Changing cloud and other adapter to work around a change in hue is also nothing we can achieve that fast.
So also nothing that helps now.

We could create issues for this and work on them later

From my point of view we need to maintain backward compatibility in this fix/optimization because users and other adapters/functionalities are used to the current featureset of the adapter, so we should try for now to stay compatible. This would mean that "color disco" is only possible under the same rules/conditions that it were before (beside I do not think that any user really want to do something like this and with the current rate limits from the bridge it will also not really be possible) and in fact combining the calls will best "compress" the calls according to the available rate limiting.

Just my 5 cents

**Comment by Apollon77** [comment]
PS: The best way (in my eyes) would be to go away from states to messages in such cases like setColor(deviceId, r,g,b,h,s,v ...) :-) This would be required for all adapters that have such a color functionality and if existing it will be used to avoid other problems ... But also: Nothing that is helping us now :-(

**Comment by jens-maus** [comment]
Well, have you actually tried if my current changes might still work ok? It could also be that due to my improvements in scheduling the hue api commands they might actually be send to the HUE bridge so fast that you wouldn't notice changing the `hue`, `saturation` and `brightness` in very short intervals like iobroker.cloud is doing.

But beside that, I hope you also see that we do have a principle problem here. Even with the current routines to combine consecutive commands to a single one you can't be 100% sure that a single command was not sent out already to the hue bridge. Actually there is currently no threshold for consecutive commands to be combined. So if e.g. the first command to change the `hue` parameter has already been processed in the last execution of `processCommands()` (see https://github.com/ioBroker/ioBroker.hue/blob/master/main.js#L466) then the other `saturation` or/and `brightness` state changed cannot be added to it anymore (because it has been sent out already). So, the currently mechanism is anyway not perfect and actually one of the reasons why the current released 1.1.1 version doesn't work so nice like the old 0.6.9 version. And that was actually the reason why I started to work on the hue adapter myself (because it was broken with taking an utterly long time to send out a command in first place).

Of course, I could now add some additional queue to the adapter and apply some threshold in time (e.g. wait XXX ms for commands to be added to the queue and then combine them) or in terms of max numbers (e.g. wait for XXX number of commands to fill in the queue and the combine them). But this will most likely introduce another delay in seeing these commands to be actually sent out to the bridge and thus will introduce a delay in seeing your sent commands being executed (seeing the color being changed).

**Comment by GermanBluefox** [comment]
> And that was actually the reason why I started to work on the hue adapter myself

I waited for this :) That some one will lost the patience and will fix this mess :)

But anyway, if we will make from 3 commands only one we can send 3 times more commands to hue bridge and so control more devices in shorter time. And we can wait just 50 ms and it is not so much.

**Comment by jens-maus** [comment]
@GermanBluefox :)

Of course, but IMHO this would be the job of the underlying hue-api node module (ioBroker.hue is currently using node-hue-api). So IMHO such a command execution queue optimization to be able to send out more commands should better be added to node-hue-api, which however is not under our control. 

I haven't checked deeply, but the more advanced `huejay` NodeJS package (https://www.npmjs.com/package/huejay) might be a better choice here. However, this would mean changing ioBroker.hue from node-hue-api to huejay, which would be a completely independent PullRequest, I guess :-)

**Comment by GermanBluefox** [comment]
>Of course, but IMHO this would be the job of the underlying 

No one will do it for us.

**Comment by andiling** [comment]
The problem is 10 pull requests in 10 seconds! If the bridge would become one request per 1 second or better 1,5 seconds it would be free for light switch requests! Can any one change this? I would test the new code! The pull loop will use no more time for this change! can we write in german?

**Comment by Garfonso** [comment]
Today I switched to this version of the adapter. And it is sufficient to have a look at the debug log, to see how superior this approach is above the "official" version. It seems like my setup needs about 15 commands to poll.
So the original version sends out 10 commands, waits 10 seconds, sends 5 commands. During those 10 seconds wait time nothing happens and control of the lamps via ioBroker is not possible at all. (i.e. 10 out of 30 seconds). 
In this version of the adapter the first 10 commands get send very fast, too, but then every second a new command is send and even during that a set command is prioritized, so controlling the lamps is possible all the time with only low delay.

For the iot discussion: I can't see how the way alexa->iot->hue should be preferable above alexa->hue. Especially because if you once paired a hue bridge with the alexa system, it seems you can not unpair it easily (at least I did not manage to and disabling the skill is not sufficient).
For ioBroker in general I tried this script:

`setState('hue.0.Philips_hue.Wolke.r', Math.random()*255);`
`setState('hue.0.Philips_hue.Wolke.g', Math.random()*255);`
`setState('hue.0.Philips_hue.Wolke.b', Math.random()*255);`

`setState("javascript.0.scriptEnabled.runOnce.testHueColor", false);`
And let it run multiple times for testing (enabling it from a button in vis). I did only see one color change on the lamp each time, no "color disco" at all. 

Please find a solution that this can go into the main branch. Because this approach is clearly superior in my setup and use cases, even if you have to let the 3->1 optimization go.

**Comment by WolfspiritM** [comment]
@GermanBluefox I'm sorry, but is this adapter dead? Should the fork be prefered over this? It seems like there is no real work and improvements going into this and this MR is open for month.

**Comment by Apollon77** [comment]
No in fact not dead ... I think we need to make a decision to accept „disco color“ effects in certain cases or find a better solution. When I remember correctly this was the last issue with this version.

**Comment by Apollon77** [comment]
Me personally would accept that PRwitj the potential Problemen mind and see if we get problem reports for these cases.

**Comment by Garfonso** [comment]
I still use the fork in my productive environment and it is much superior compared to the stable version.
And I use the color setting quite often.

**Comment by jens-maus** [comment]
@Apollon77 I would also say that it would be worth a try to merge my PR and see if there will be any larger amount of reports coming up with actual issues related to my changes. My guess is that not many installations will see a negative effect, if any at all.

**Comment by Apollon77** [comment]
Ok i will merge it once back from vacation latest in a week.

**Comment by Apollon77** [comment]
So here we go. :-)

**Comment by Apollon77** [comment]
I merged it and updated the deps (especially bottleneck!) and it is now on GitHub!

Can someone please do a final test that the changed deps do not had negative effetcs before I publish it to npm ?!

**Comment by jens-maus** [comment]
@Apollon77 Thanks for the merge (finally!) ;-) And what do you mean with bottleneck is not on GitHub?!? It is (https://github.com/SGrondin/bottleneck). And I will test your merged version ASAP.

**Comment by Apollon77** [comment]
hehe not = now :-) sorry ... auto correction

**Comment by Apollon77** [comment]
@jens-maus or someone else: Did someone tested?

**Comment by jens-maus** [comment]
@Apollon77 Hab es gerade getestet und sieht soweit alles i.O. aus. Meines Erachtens kann das so auf die Menschheit losgelassen werden ;-)

**Comment by Apollon77** [comment]
published to npm latest beginning tomorrow ... then we see :-)

**Comment by SGrondin** [comment]
Glad to see this was merged! I've been following and reviewing the code in this PR for the last 2 months. Really exciting to see how you used bottleneck. 😄

**Comment by jens-maus** [comment]
@SGrondin Thank YOU for this great nodejs class allowing to do fine grained rate limiting. It really helped a lot to get this Philips Hue Adapter into a better working state with the limitating API of the Hue bridge!

**Pull request merged**
