### PR TITLE
added updateSensorStat for CLIPGenericFlag sensors #328

### PR DESCRIPTION
**Pull request by Eistee82**
this change is untested!!!

### CODE REVIEW

**Comment by foxriver76** [comment]
You can install from your branch via `iob url` command to test it.

**Comment by Eistee82** [comment]
Hi. I have tested it successful. Now we can set CLIP Generic Flag sensors in iobroker.

**Comment by foxriver76** [comment]
Thank you

**Comment by Eistee82** [comment]
Is it posible to make a new release?

**Comment by foxriver76** [comment]
Currently on vacation - ping me in one week or @Apollon77 is that kind and finds some time.

**Comment by Apollon77** [comment]
come soon

**Comment by foxriver76** [comment]
Gracie. ;-)

**Pull request merged**
