### PR TITLE
Compact mode, light naming, object grouping

### PR DESCRIPTION
**Pull request by BasGo**
First of all I changed the adapter to be ready for your new compact mode.

The main reason to create this PR was, that I have two lights with the name "Regal" in two different rooms and I don't want to rename them to **Room1.Regal** and **Room2.Regal**, it would break my WAF (woman acceptance factor) at home ;-) So I implemented lights to use their unique ID as ID and to have their "real" name (extended with concatenated room information) as common name.

Additionally I've implemented a grouping for lights, sensors and group.

My local tests have been successful.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Is it not the breaking change? 
https://github.com/ioBroker/ioBroker.hue/pull/54/files#diff-7a9076d6d94e62c13d641aa71f19ae8eR1067
Because the IDs will be changed.

**Comment by Apollon77** [comment]
Hm yes this is breaking ...

**Comment by BasGo** [comment]
We can stop this PR. I will create a new PR with just containing the compact mode.

How should I handle the breaking change after having implemented the compact mode? Actually I'm not able to address two devices having the same name (light "Regal" in two rooms) so I think the best was would be to use some kind of unique IDs for devices. What do you think?

**Comment by GermanBluefox** [comment]
Breaking changes are not fatal. We just increase the major number and write about it in readme.
But I think it is good idea to split "compact" and "rooms" changes into 2 PRs.
First please compact mode :)

**Comment by BasGo** [comment]
No problem -> see #55 which is reduced to an implementation for the compact mode (v1.1.2) without any breaking change. The other change will follow ...

**Pull request closed without merging**
